language: java
jdk:
- openjdk14
sudo: false

script: mvn clean package

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
    - qqqiva@gmail.com
    on_success: never
    on_failure: always

env:
  global:
  - CODECOV_TOKEN=""